### ISSUE TITLE
Kedro Viz build not displaying

### ISSUE THREAD

**Issue by butterlyn** [kedro-org/kedro-viz#1721] opened 2024-01-29 09:40 UTC
## Description
Get a "Oops, there's nothing to see here" when deploying Kedro Viz dashboard using `kedro viz build` files. Note that Kedro Viz properly renders the dashboard when using `kedro viz run`, but cannot run when using `kedro viz build` files.

## Context
Unable to share or distribute Kedro Viz in Azure Static Web Apps, or via .html files.

## Steps to Reproduce

1. Create a fresh Kedro template project (`kedro new`, no starters) with an example pipeline
2. Install `requirements.txt`
3. `kedro viz build`
4. Open `index.html` file in `build/` folder, or deploy to Azure Static Web App (they yield the same error)

## Expected Result
View of example pipeline.

## Actual Result

Kedro dashboard with "Oops, there's nothing to see here", with a spinning wheel that never goes away.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Google Chrome
* Operating system and version: Ubuntu 22.04
* Kedro version used (if relevant): Kedro Viz 7.1.0, Kedro 0.19.2
* Python dependencies: default dependencies found in template `requirements.txt` file.
* OS: Ubuntu 22.04
* Python version used (if relevant): 3.11.7

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by astrojuanlu** [comment] 2024-01-29 17:22
Thanks for reporting this @butterlyn! Any chance you can share the resulting files on some file exchange site or even gist.github.com, so we can try to open them and narrow down where the problem is?

**Comment by butterlyn** [comment] 2024-01-30 08:05
> Thanks for reporting this @butterlyn! Any chance you can share the resulting files on some file exchange site or even gist.github.com, so we can try to open them and narrow down where the problem is?


Please find repo with source code (1 node) and build files:
https://github.com/butterlyn/kedro-viz-issue

**Comment by astrojuanlu** [comment] 2024-01-30 09:26
I can see them:

![image](https://github.com/kedro-org/kedro-viz/assets/316517/60197dda-ed9a-4be5-861c-02e88b31eeb5)

BUT only if I launch a `python -m http.server`. Otherwise, if I open the `index.html` directly, I can reproduce the issue:

![image](https://github.com/kedro-org/kedro-viz/assets/316517/d7e9793f-8637-4234-be3d-8b721e55bdc2)

**Comment by rashidakanchwala** [comment] 2024-01-30 10:52
@butterlyn - Kedro-viz is a React application with multiple bundled JavaScript and CSS files that compose the entire application. Sharing only the index.html file won't suffice. Additionally, when deploying to an Azure Web App, it's crucial to upload the entire build folder to the storage container, not just the index.html file.

**Comment by astrojuanlu** [comment] 2024-01-30 11:25
Notice though that I unzipped the whole directory. According to the browser inspector tools, there were some CORS issues when _not_ using an HTTP server.

**Comment by butterlyn** [comment] 2024-01-30 14:21
> @butterlyn - Kedro-viz is a React application with multiple bundled JavaScript and CSS files that compose the entire application. Sharing only the index.html file won't suffice. Additionally, when deploying to an Azure Web App, it's crucial to upload the entire build folder to the storage container, not just the index.html file.

Apologies for the confusion, I meant when sharing the entire `build/` folder and trying to open the application by opening `index.html` in a browser. When uploading the whole of `build/` to Azure Static Web Apps (or sharing the whole `build/` folder locally and opening `index.html` in a browser) the above issue still occurs.

**Comment by butterlyn** [comment] 2024-02-06 01:06
@rashidakanchwala Getting the impression that this isn't an intended feature of Kedro Viz. Should label this issue as "won't fix"?

**Comment by astrojuanlu** [comment] 2024-02-06 07:39
@butterlyn Some of the status changes might not be visible to you (attaching screenshot for reference, can you confirm you see or don't see it?) but we added this to our backlog already!

![image](https://github.com/kedro-org/kedro-viz/assets/316517/88d1800c-ce49-4477-bfc7-4e5d47e0131b)

**Comment by butterlyn** [comment] 2024-02-06 08:00
@astrojuanlu Awesome 😁 will try and submit a pull request for a simpler issue to chip in (this one's a bit beyond me)

That status update is hidden for me

**Comment by rashidakanchwala** [comment] 2024-02-06 08:46
Hi, @butterlyn,

We've had an overwhelming week with people on holidays, so we apologize for the delays in getting back to you. 

The reason for your issue may be related to how you access the Azure Static Web App.

You need to enable static hosting on your Azure storage container. Please refer to the screenshot below.

<img width="1706" alt="Screenshot 2024-02-06 at 08 37 55" src="https://github.com/kedro-org/kedro-viz/assets/37628668/b9af7e66-316f-45d1-8514-71d4a239e04b">

You can copy/paste the primary endpoint mentioned for your static app as that will be the link you share with others.  

Once you have enabled static website, within your container, you will find a $web folder. Inside this folder, you should upload the contents of the build folder so that they are in the root of the $web folder.

<img width="836" alt="Screenshot 2024-02-06 at 08 41 25" src="https://github.com/kedro-org/kedro-viz/assets/37628668/eb823e4d-5a22-4c78-b4cc-d84090ca1e18">

Once you've completed these steps, you'll be able to access your Kedro-viz app via the primary endpoint.

**Comment by astrojuanlu** [comment] 2024-02-09 16:55
For the record, note that this problem not only arises on cloud environments, but also locally https://github.com/kedro-org/kedro-viz/issues/1721#issuecomment-1916410936

**Comment by ravi-kumar-pilla** [comment] 2024-02-13 15:17
> For the record, note that this problem not only arises on cloud environments, but also locally [#1721 (comment)](https://github.com/kedro-org/kedro-viz/issues/1721#issuecomment-1916410936)

This should be an expected behavior as you would need a web server to run the static site. If not it will be just like opening a file in the browser.

**Comment by rashidakanchwala** [comment] 2024-02-19 09:49
Closing this issue as it is resolved.

**Closed by rashidakanchwala** 2024-02-19 09:49 UTC
Labels: Issue: Bug Report
