### ISSUE TITLE
Conflicting sqlalchemy versions with Kedro

### ISSUE THREAD

**Issue by melvinkokxw** [kedro-org/kedro-viz#1302] opened 2023-03-29 08:44 UTC
## Description
`kedro-viz==6.0.0` has a dependency of `sqlalchemy~=2.0` while `kedro==0.18.7` (latest at the time of writing) has a dependency of `SQLAlchemy~=1.2`, which causes a conflict when resolving dependencies, e.g. via `pip-compile`.

## Context
I was trying to `pip-compile` my dependencies, and I have both `kedro-viz~=6.0` and `kedro~=0.18.7` in my input dependencies. 

## Steps to Reproduce

1. Create an input requirements file (e.g. `requirements.in`) with both `kedro-viz~=6.0` and `kedro~=0.18.7`
2. Run `pip-compile`, e.g. `pip-compile --output-file=src/requirements.txt src/requirements.in`

## Expected Result
A `requirements.txt` file should be compiled with no conflicts.

## Actual Result
This error is thrown:
```
There are incompatible versions in the resolved dependencies:
  SQLAlchemy~=1.2 (from kedro[pandas]==0.18.7->-r src/requirements.in (line xx))
  sqlalchemy~=2.0 (from kedro-viz==6.0.0->-r src/requirements.in (line yy))
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: NA
* Operating system and version: Windows 10 Enterprise for Virtual Desktops version 22H2
* NodeJS version used (if relevant): NA
* Kedro version used (if relevant): 0.18.7
* Python version used (if relevant): 3.8.16

`pip-tools` version is 6.12.3, `pip` version is 23.0.1
## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by astrojuanlu** [comment] 2023-03-29 09:09
Hi @melvinkokxw, thanks for reporting! This is a duplicate of https://github.com/kedro-org/kedro/issues/2474 and was addressed yesterday by https://github.com/kedro-org/kedro-viz/pull/1300. It will be fixed in the next release

**Comment by tynandebold** [comment] 2023-03-30 11:36
@melvinkokxw the release it out now. [See it here](https://pypi.org/project/kedro-viz/).

Thank you for raising this issue! I'll close as completed.

**Closed by tynandebold** 2023-03-30 11:36 UTC
Labels: Issue: Bug Report
