### ISSUE TITLE
Kedro-viz displaying empty pipeline visualization

### ISSUE THREAD

**Issue by scarvajalg** [kedro-org/kedro-viz#754] opened 2022-02-22 23:26 UTC
## Description
When I run kedro-viz from the command line, I get an error. I work with pyspark and python 

## Context
Can't visualize kedro pipelines and datasets graph

## Steps to Reproduce
I tried with two different kedro versions 4.0.0 and 4.3.1

## Expected Result
Visualize the pipelines graph in the browser 

## Actual Result
I get the following errors

```
importlib; see the module's documentation for alternative uses
  from imp import load_source
Traceback (most recent call last):
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file
```

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/kedro_viz/launchers/cli.py", line 129, in viz
    run_server(**run_server_kwargs)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/kedro_viz/server.py", line 110, in run_server
    populate_data(data_access_manager, catalog, pipelines, session_store_location)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/kedro_viz/server.py", line 65, in populate_data
    Base.metadata.create_all(bind=database_engine)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3116, in _run_ddl_visitor
    with self.begin() as conn:
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3032, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3253, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/scarvajalg/PycharmProjects/data_engineering/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
kedro.framework.cli.utils.KedroCliError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Run with --verbose to see the full exception
Error: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Google Chrome 96.0.4664.110
* Operating system and version: MacOS Monterrey 12.2.1
* NodeJS version used (if relevant):
* Kedro version used (if relevant): 0.17.6
* Python version used (if relevant): 3.8.12
* Spark version used: 3.2.1
* Scala version used: 2.12.15
* Java version used: 1.8.0_321

## Checklist
- [ ] visualization

**Comment by tynandebold** [comment] 2022-02-23 10:34
Hey @scarvajalg, thank you for reporting this.

Taking a quick look at the error messages, there seems to be something amiss with sqlite, and therefore it could be something to do with experiment tracking. Are you trying to enable that feature in Kedro-Viz?

If so, have you followed the [usage instructions in the readme](https://github.com/kedro-org/kedro-viz#experiment-tracking-usage) in order to enable it?

**Comment by scarvajalg** [comment] 2022-02-23 15:04
Hi!

I fix the error with sqlite. Now kedro-viz works but I can not visualize the pipelines:
![kedro-viz](https://user-images.githubusercontent.com/31626241/155346060-72dacfe8-46ce-4e03-b0d5-5fba16a51027.png)

Kedro-viz is empty. Why kedro-viz can't recognize the datasets and pipelines?

**Comment by rashidakanchwala** [comment] 2022-02-28 13:41
Hi @scarvajalg, 
What happens when you open http://localhost:4141/api/main -- do you see a json with nodes, pipelines. Please do share a screenshot.

**Comment by scarvajalg** [comment] 2022-02-28 14:10
Hi!
This is the result:
![Captura de Pantalla 2022-02-28 a la(s) 9 08 20 a m](https://user-images.githubusercontent.com/31626241/155997144-48d3491b-eba1-47c7-bf6e-a490cb38e6be.png)

**Comment by tynandebold** [comment] 2022-03-07 16:08
Hi @scarvajalg, thank you for the screenshot!

I observe that you don't seem to have any nodes, edges, or layers in your screenshot. @AntonyMilneQB do you have any thoughts on why these arrays would be empty?

**Comment by AntonyMilneQB** [comment] 2022-03-08 11:09
@tynandebold I wonder if this is the same issue we fixed in https://github.com/kedro-org/kedro-viz/pull/729 (but isn't released yet).

@scarvajalg what command exactly are you running to start `kedro viz`? If you're using the `--pipeline` flag, does it work without that, i.e. just a pure `kedro viz`?

**Comment by scarvajalg** [comment] 2022-03-08 13:54
I executed both `kedro viz` and `kedro viz --pipeline` and I got the same result, an empty visualization

**Comment by scarvajalg** [comment] 2022-03-09 14:31
This is the output of `kedro registry list`
![Captura de Pantalla 2022-03-09 a la(s) 9 30 08 a m](https://user-images.githubusercontent.com/31626241/157461863-d5277f7e-968b-41aa-820f-f83bb38b474a.png)
`pipeline_registry.py `:
```
def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from a pipeline name to a ``Pipeline`` object.
    """
    ddv_master = premaster_pipeline() + sunarp_pipeline() + master_pipeline()
    udv_pacifico = (
        bienes_generales_pipeline() +
        persona_pipeline() +
        poliza_pipeline() +
        producto_pipeline() +
        referencia_pipeline() +
        siniestro_pipeline()
    )
    udv_bcp = data_bcp_pipeline()
    return {
        "__default__": Pipeline([]),
        "bienes_generales": bienes_generales_pipeline(),
        "great_expectations": great_expectations_pipeline(),
        "data_bcp": data_bcp_pipeline(),
        "ddv_master": ddv_master,
        "dom_referencia": dom_referencia_pipeline(),
        "master": master_pipeline(),
        "dom_persona": dom_persona_pipeline(),
        "dom_poliza": dom_poliza_pipeline(),
        "persona": persona_pipeline(),
        "poliza": poliza_pipeline(),
        "producto": producto_pipeline(),
        "premaster": premaster_pipeline(),
        "referencia": referencia_pipeline(),
        "siniestro": siniestro_pipeline(),
        "sunarp": sunarp_pipeline(),
        "udv_pacifico": udv_pacifico,
        "udv_bcp": udv_bcp,
        "um_score_buro": um_score_buro_pipeline(),
        "universal": udv_pacifico + udv_bcp,
    }
```

**Comment by AntonyMilneQB** [comment] 2022-03-09 17:28
Ah ok, I think the problem is going to be that you have an empty `__default__` pipeline. I suspect that this will be fixed when https://github.com/kedro-org/kedro-viz/pull/729 is released.

For the time being, I think the easiest fix is to populate `__default__` with something, e.g. `"__default__": bienes_generales_pipeline()`. Or probably even just a completely fake pipeline like `"__default__": Pipeline([node(lambda: None, None, "x")])`

**Comment by scarvajalg** [comment] 2022-03-09 20:12
As you suggest, I populate `__default__` with a fake pipeline. 
Now, when I execute kedro viz I can see just one pipeline (`persona pipeline`) but I can't visualize the other pipelines or all of them. I tried `kedro viz --pipeline` to visualize other pipeline, and it's empty. It seems that now kedro viz only recognize persona pipeline.

**Comment by AntonyMilneQB** [comment] 2022-03-11 16:07
Hmm, this is weird. Please could you try running the following to install a version of kedro-viz that includes the fix https://github.com/kedro-org/kedro-viz/pull/729.
```
pip uninstall kedro-viz
pip install https://github.com/kedro-org/kedro-viz/raw/test/main-package/package/dist/kedro_viz-4.3.1-py3-none-any.whl
```

**Comment by scarvajalg** [comment] 2022-03-15 19:46
I tried `kedro viz --pipeline` and I can visualize the pipeline I want to. But I can't visualize all the pipelines of the project. My project is big, there is a limit of pipelines or items that kedro viz can create in the visualization? Maybe that's the problem I can't visualize all the pipelines.

**Comment by tynandebold** [comment] 2022-03-15 21:59
If possible, could you please create a repo and share the link with us? That'll help us find a solution faster.

**Comment by tynandebold** [comment] 2022-03-21 15:37
Hi @scarvajalg. I'm wondering if you're still having issues with this?

**Comment by tynandebold** [comment] 2022-03-21 16:39
Got it, thank you for the update. Would it be possible for you to create a separate, simplified repository that demos the same problem you're facing?

**Comment by jw-cpnet** [comment] 2022-03-22 02:51
I have got the same issue. All my pipelines are empty.

```
kedro viz --pipeline history
2022-03-22 10:49:34,616 - kedro_viz.integrations.pypi - INFO - Checking for update...
2022-03-22 10:49:35,309 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2022-03-22 10:49:35,334 - kedro.config.config - INFO - Config from path `/home/jj/Git/etl-projects/conf/local` will override the following existing top-level config keys: machine_input
2022-03-22 10:49:36,191 - kedro.config.config - INFO - Config from path `/home/jj/Git/etl-projects/conf/local` will override the following existing top-level config keys: store_machine
INFO:     Started server process [114880]
2022-03-22 10:49:37,435 - uvicorn.error - INFO - Started server process [114880]
INFO:     Waiting for application startup.
2022-03-22 10:49:37,436 - uvicorn.error - INFO - Waiting for application startup.
INFO:     Application startup complete.
2022-03-22 10:49:37,437 - uvicorn.error - INFO - Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:4141 (Press CTRL+C to quit)
2022-03-22 10:49:37,437 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:4141 (Press CTRL+C to quit)

(google-chrome:115008): Gtk-WARNING **: 10:49:37.672: Theme parsing error: gtk.css:5822:26: '-shadow' is not a valid color name

(google-chrome:115008): Gtk-WARNING **: 10:49:37.673: Theme parsing error: gtk.css:5825:14: not a number

(google-chrome:115008): Gtk-WARNING **: 10:49:37.673: Theme parsing error: gtk.css:5826:13: not a number

(google-chrome:115008): Gtk-WARNING **: 10:49:37.673: Theme parsing error: gtk.css:5827:11: Expected a length
Opening in existing browser session.
INFO:     127.0.0.1:33666 - "GET / HTTP/1.1" 200 OK
[115049:115049:0100/000000.879141:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
INFO:     ('127.0.0.1', 33670) - "WebSocket /graphql" [accepted]
2022-03-22 10:49:38,084 - uvicorn.error - INFO - ('127.0.0.1', 33670) - "WebSocket /graphql" [accepted]
INFO:     127.0.0.1:33666 - "GET /api/main HTTP/1.1" 200 OK
INFO:     127.0.0.1:33666 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:33672 - "GET /manifest.json HTTP/1.1" 404 Not Found
INFO:     ('127.0.0.1', 33674) - "WebSocket /graphql" [accepted]
2022-03-22 10:49:39,240 - uvicorn.error - INFO - ('127.0.0.1', 33674) - "WebSocket /graphql" [accepted]
INFO:     ('127.0.0.1', 33676) - "WebSocket /graphql" [accepted]
2022-03-22 10:49:39,511 - uvicorn.error - INFO - ('127.0.0.1', 33676) - "WebSocket /graphql" [accepted]
INFO:     ('127.0.0.1', 33678) - "WebSocket /graphql" [accepted]
2022-03-22 10:49:40,252 - uvicorn.error - INFO - ('127.0.0.1', 33678) - "WebSocket /graphql" [accepted]

```

**Comment by jw-cpnet** [comment] 2022-03-22 02:53
```
kedro registry list
- __default__
- api
- erp
- history
- machine
- report
```

**Comment by AntonyMilneQB** [comment] 2022-03-22 09:20
Hi @jw-cpnet, please could you try running the following and see if that fixes it?
```
pip uninstall kedro-viz
pip install https://github.com/kedro-org/kedro-viz/raw/test/main-package/package/dist/kedro_viz-4.3.1-py3-none-any.whl
```

**Comment by jw-cpnet** [comment] 2022-03-28 01:46
Thank you! @AntonyMilneQB 

The fix works perfectly! And yes, kedro viz (before fixing) without pipeline argument works too.

**Comment by AntonyMilneQB** [comment] 2022-03-28 08:36
Excellent, thanks very much for letting us know. This fix will be included in the next release of kedro-viz, so when that is released you should just be able to `pip install kedro-viz==4.3.2` and all will be good.

**Comment by yetudada** [comment] 2022-04-06 14:01
It looks like this issue is resolved! Thanks for raising it @jw-cpnet and have an awesome day! 🚀

**Closed by yetudada** 2022-04-06 14:01 UTC
Labels: Issue: Bug Report
