### ISSUE TITLE
Kedro Viz command raised MemoryDataSet error (5.2.0)

### ISSUE THREAD

**Issue by YoroiiHatemaki** [kedro-org/kedro-viz#1228] opened 2023-01-20 12:55 UTC
Hey, we've been successfully using kedro-viz 5.1.1 in our kedro project and today I've tried to switch to kedro-viz 5.2.0. Suddenly, the "kedro viz" command raises an error and fails to complete. 

This is the error: 
`kedro.io.core.DataSetError: Data for MemoryDataSet has not been saved yet.
kedro.framework.cli.utils.KedroCliError: Data for MemoryDataSet has not been saved yet.
Run with --verbose to see the full exception
Error: Data for MemoryDataSet has not been saved yet.
`
Switching back to kedro-viz 5.1.1 allows to successfully run "kedro viz" immediately. Any ideas how we can fix that or what may be causing it? Thanks in advance ^^

**Comment by tynandebold** [comment] 2023-01-20 14:10
Thanks for reporting the issue @YoroiiHatemaki. I think this is the same problem as #1226. What do you say @jmholzer?

For now, please continue to use version `5.1.1` of Kedro-Viz until we release a fix for this problem.

**Comment by jmholzer** [comment] 2023-01-20 15:06
> Thanks for reporting the issue @YoroiiHatemaki. I think this is the same problem as #1226. What do you say @jmholzer?
> 
> For now, please continue to use version `5.1.1` of Kedro-Viz until we release a fix for this problem.

It's definitely related, probably closely enough that it's the same problem, though I still haven't been able to reproduce #1226, I'll keep looking into both of these.

**Comment by jmholzer** [comment] 2023-01-20 16:36
Hey @YoroiiHatemaki, thanks for the report. Unfortunately I can't reproduce the error locally with a simple pipeline, could you please show us your catalog?

**Comment by YoroiiHatemaki** [comment] 2023-01-23 09:05
Hey @jmholzer, sadly I'm not allowed to show the whole catalog. However, I've found that we have 3 memory datasets in the catalog, and one of them is used both as input and as output in one of the nodes. My guess is that kedro-viz 5.1.1 allowed you to generate a visualization without checking whether all memory datasets have been saved, while kedro-viz 5.2.0 specifically checks for that. Do you think that this might be the issue?

**Comment by AntonyMilneQB** [comment] 2023-01-23 10:11
I think this is probably unrelated to #1226 and instead to do with https://github.com/kedro-org/kedro-viz/pull/1113 instead.

**Comment by KikiCS** [comment] 2023-01-23 10:33
I got the same problem. Tried fixing by adding all MemoryDatasets to catalog.yml and got the same message. Then I saved fake data in S3 using the path provided in catalog.yml, and still got the same error message from kedro-viz.
Downgrading to 5.1.1 fixed the problem.

**Comment by tynandebold** [comment] 2023-01-23 12:02
@AntonyMilneQB it may not be related to #1113 if it works in `5.1.1`. Could be another issue with Viz's integration with `kedro-datasets`?

**Comment by AntonyMilneQB** [comment] 2023-01-23 12:25
@tynandebold but #1113 was released in 5.2.0 and not 5.1.1? I think there's probably two separate bugs here, both of which were introduced in 5.2.0.

**Comment by tynandebold** [comment] 2023-01-23 13:41
True.

**Comment by jmholzer** [comment] 2023-01-23 17:04
Hey @YoroiiHatemaki and @KikiCS, thanks for all your help so far. I've found at least one way to reproduce this error on `5.2.0`. With version `5.1.1`, passing an undefined parameter to a node would trigger a warning, though with version `5.2.0`,  an unhandled exception is raised instead.

Could you please tell me if you are passing parameters that are not defined in your config to nodes in your projects?

One way to tell is to check whether you get this warning when you run `kedro viz` with version `5.1.1` installed:
<img width="434" alt="Screenshot 2023-01-23 at 16 47 39" src="https://user-images.githubusercontent.com/37243923/214102025-1d9e4848-caee-4a7a-a28c-f829cabe85c1.png">

Alternatively, you could run the following 4 lines of code after launching `kedro ipython`:

```
from kedro.pipeline.modular_pipeline import _is_parameter
inputs = set().union(*(node.inputs for node in sum(pipelines.values()).nodes))
undefined_params = set(filter(_is_parameter, inputs)) - set(catalog.list())
print(undefined_params)
```

Thanks for your help and patience.

**Comment by YoroiiHatemaki** [comment] 2023-01-24 09:33
@jmholzer Thank you, that was indeed an issue. After adding the parameter to the catalog, kedro viz 5.2.0 now works. Thanks a lot again!

**Closed** 2023-01-27 11:49 UTC
Labels: Issue: Bug Report
